<?php
/**
 * SetProductOptionDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BackOffice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: backoffice-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\BackOffice\Model;

use \ArrayAccess;
use \Aurigma\BackOffice\ObjectSerializer;

/**
 * SetProductOptionDto Class Doc Comment
 *
 * @category Class
 * @description Product option create or update operation parameters.
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SetProductOptionDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SetProductOptionDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uid' => 'string',
        'title' => 'string',
        'description' => 'string',
        'tooltip' => 'string',
        'sort_index' => 'int',
        'use_for_design_binding' => 'bool',
        'use_for_mockup_binding' => 'bool',
        'use_for_document_binding' => 'bool',
        'values' => '\Aurigma\BackOffice\Model\SetProductOptionValueDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uid' => null,
        'title' => null,
        'description' => null,
        'tooltip' => null,
        'sort_index' => 'int32',
        'use_for_design_binding' => null,
        'use_for_mockup_binding' => null,
        'use_for_document_binding' => null,
        'values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uid' => true,
        'title' => true,
        'description' => true,
        'tooltip' => true,
        'sort_index' => false,
        'use_for_design_binding' => false,
        'use_for_mockup_binding' => false,
        'use_for_document_binding' => false,
        'values' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uid' => 'uid',
        'title' => 'title',
        'description' => 'description',
        'tooltip' => 'tooltip',
        'sort_index' => 'sortIndex',
        'use_for_design_binding' => 'useForDesignBinding',
        'use_for_mockup_binding' => 'useForMockupBinding',
        'use_for_document_binding' => 'useForDocumentBinding',
        'values' => 'values'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uid' => 'setUid',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'tooltip' => 'setTooltip',
        'sort_index' => 'setSortIndex',
        'use_for_design_binding' => 'setUseForDesignBinding',
        'use_for_mockup_binding' => 'setUseForMockupBinding',
        'use_for_document_binding' => 'setUseForDocumentBinding',
        'values' => 'setValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uid' => 'getUid',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'tooltip' => 'getTooltip',
        'sort_index' => 'getSortIndex',
        'use_for_design_binding' => 'getUseForDesignBinding',
        'use_for_mockup_binding' => 'getUseForMockupBinding',
        'use_for_document_binding' => 'getUseForDocumentBinding',
        'values' => 'getValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('tooltip', $data ?? [], null);
        $this->setIfExists('sort_index', $data ?? [], null);
        $this->setIfExists('use_for_design_binding', $data ?? [], null);
        $this->setIfExists('use_for_mockup_binding', $data ?? [], null);
        $this->setIfExists('use_for_document_binding', $data ?? [], null);
        $this->setIfExists('values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uid
     *
     * @return string|null
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param string|null $uid Product option UID.
     *
     * @return self
     */
    public function setUid($uid)
    {
        if (is_null($uid)) {
            array_push($this->openAPINullablesSetToNull, 'uid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('uid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Product option title.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            array_push($this->openAPINullablesSetToNull, 'title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Product option description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets tooltip
     *
     * @return string|null
     */
    public function getTooltip()
    {
        return $this->container['tooltip'];
    }

    /**
     * Sets tooltip
     *
     * @param string|null $tooltip Product option tooltip.
     *
     * @return self
     */
    public function setTooltip($tooltip)
    {
        if (is_null($tooltip)) {
            array_push($this->openAPINullablesSetToNull, 'tooltip');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tooltip', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tooltip'] = $tooltip;

        return $this;
    }

    /**
     * Gets sort_index
     *
     * @return int|null
     */
    public function getSortIndex()
    {
        return $this->container['sort_index'];
    }

    /**
     * Sets sort_index
     *
     * @param int|null $sort_index Product option sort index.
     *
     * @return self
     */
    public function setSortIndex($sort_index)
    {
        if (is_null($sort_index)) {
            throw new \InvalidArgumentException('non-nullable sort_index cannot be null');
        }
        $this->container['sort_index'] = $sort_index;

        return $this;
    }

    /**
     * Gets use_for_design_binding
     *
     * @return bool|null
     */
    public function getUseForDesignBinding()
    {
        return $this->container['use_for_design_binding'];
    }

    /**
     * Sets use_for_design_binding
     *
     * @param bool|null $use_for_design_binding Specifies if the option is used for design binding.
     *
     * @return self
     */
    public function setUseForDesignBinding($use_for_design_binding)
    {
        if (is_null($use_for_design_binding)) {
            throw new \InvalidArgumentException('non-nullable use_for_design_binding cannot be null');
        }
        $this->container['use_for_design_binding'] = $use_for_design_binding;

        return $this;
    }

    /**
     * Gets use_for_mockup_binding
     *
     * @return bool|null
     */
    public function getUseForMockupBinding()
    {
        return $this->container['use_for_mockup_binding'];
    }

    /**
     * Sets use_for_mockup_binding
     *
     * @param bool|null $use_for_mockup_binding Specifies if the option is used for mockup binding.
     *
     * @return self
     */
    public function setUseForMockupBinding($use_for_mockup_binding)
    {
        if (is_null($use_for_mockup_binding)) {
            throw new \InvalidArgumentException('non-nullable use_for_mockup_binding cannot be null');
        }
        $this->container['use_for_mockup_binding'] = $use_for_mockup_binding;

        return $this;
    }

    /**
     * Gets use_for_document_binding
     *
     * @return bool|null
     */
    public function getUseForDocumentBinding()
    {
        return $this->container['use_for_document_binding'];
    }

    /**
     * Sets use_for_document_binding
     *
     * @param bool|null $use_for_document_binding Specifies if the option is used for document binding.
     *
     * @return self
     */
    public function setUseForDocumentBinding($use_for_document_binding)
    {
        if (is_null($use_for_document_binding)) {
            throw new \InvalidArgumentException('non-nullable use_for_document_binding cannot be null');
        }
        $this->container['use_for_document_binding'] = $use_for_document_binding;

        return $this;
    }

    /**
     * Gets values
     *
     * @return \Aurigma\BackOffice\Model\SetProductOptionValueDto[]|null
     */
    public function getValues()
    {
        return $this->container['values'];
    }

    /**
     * Sets values
     *
     * @param \Aurigma\BackOffice\Model\SetProductOptionValueDto[]|null $values A list of product option values.
     *
     * @return self
     */
    public function setValues($values)
    {
        if (is_null($values)) {
            array_push($this->openAPINullablesSetToNull, 'values');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('values', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['values'] = $values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


